<a href="https://colab.research.google.com/github/tenghjjp-blip/test/blob/main/%E6%A4%8D%E7%94%B0%E3%82%B5%E3%83%96%E3%82%BC%E3%83%9F_24_%E5%95%8F%E9%A1%8C9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 問題９

1月から3月に生まれたいわゆる早生まれの人は、4月から6月に生まれた人に比較して、同学年において他の人に比べて年齢が半年から1年少ないために、不利だといわれている。このことを発達心理学では、相対年齢効果という。

この問題では、TINSS（IrendsinMathematicsandScienceStudy，「国際数学・理科教育動向調査」）のデータを用いて、中学2年における、生まれ月が数学の成績に与える影響について分析しよう。

##手順
①データの読み込み・データの中身の確認

②欠損値の確認

③データ型の確認

④回帰分析

（多重共線性の確認）

In [1]:
from scipy.stats import t, f
import numpy as np
import pandas as pd
from statsmodels.formula.api import ols
import matplotlib.pyplot as plt
# import wooldridge

In [9]:
#①データの読み込み
df = pd.read_excel("/content/timss.xlsx")
df.head()
# データはドライブからダウンロード
# ファイルのパス名（/content/timss.xlsx)は自身の環境に合わせて変更して。
# パス名とはファイルの位置のこと
# ファイルのパス名は左のフォルダっぽいアイコンを推して、「timss.xlsx」を見つけよう
# 詳しくは、次のリンクをチェック　https://interface.cqpub.co.jp/ail01/

,idschool,gender,numpeople,mathscore,sciencescore,agese_q2,agese_q3,agese_q4,comu_1,comu_2,...,mothereduc_3,mothereduc_4,mothereduc_5,mothereduc_6,fathereduc_1,fathereduc_2,fathereduc_3,fathereduc_4,fathereduc_5,fathereduc_6
0,1,girl,6,131.718887,142.569763,0,0,1,1,0,...,0,0,0,1,0,0,0,0,0,1
1,1,girl,4,145.550461,159.221176,0,1,0,1,0,...,0,1,0,0,0,0,0,1,0,0
2,1,girl,5,139.960510,140.885910,0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0
3,1,girl,3,145.478806,164.459839,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,1,boy,4,164.112015,160.343750,1,0,0,1,0,...,1,0,0,0,0,0,0,0,0,1

In [12]:
df.dtypes

idschool          int64
gender           object
numpeople        object
mathscore       float64
sciencescore    float64
agese_q2          int64
agese_q3          int64
agese_q4          int64
comu_1            int64
comu_2            int64
comu_3            int64
comu_4            int64
comu_5            int64
comu_6            int64
computer          int64
book_1            int64
book_2            int64
book_3            int64
book_4            int64
book_5            int64
mothereduc_1      int64
mothereduc_2      int64
mothereduc_3      int64
mothereduc_4      int64
mothereduc_5      int64
mothereduc_6      int64
fathereduc_1      int64
fathereduc_2      int64
fathereduc_3      int64
fathereduc_4      int64
fathereduc_5      int64
fathereduc_6      int64
dtype: object

In [13]:
df.describe()

,idschool,mathscore,sciencescore,agese_q2,agese_q3,agese_q4,comu_1,comu_2,comu_3,comu_4,...,mothereduc_3,mothereduc_4,mothereduc_5,mothereduc_6,fathereduc_1,fathereduc_2,fathereduc_3,fathereduc_4,fathereduc_5,fathereduc_6
count,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,...,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000,4536.000000
mean,73.182099,149.968223,149.996500,0.272046,0.247575,0.229056,0.243386,0.395282,0.111772,0.160494,...,0.181217,0.166446,0.007275,0.291446,0.037919,0.266975,0.053792,0.283730,0.018519,0.339065
std,42.221116,9.932715,9.974685,0.445062,0.431651,0.420272,0.429174,0.488965,0.315121,0.367104,...,0.385240,0.372522,0.084993,0.454479,0.191021,0.442428,0.225631,0.450857,0.134832,0.473444
min,1.000000,107.280724,99.631523,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37.000000,143.257156,143.785873,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,73.000000,149.563766,149.959991,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,108.000000,156.443726,156.508316,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000
max,148.000000,178.946915,194.114349,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## (a)
数学の成績(mathscore)を、生まれた四半期のダミー変数（agese_q2, agese_q3, agese_q4）に（定数項を含んで）回帰して、早生まれの人の成績が、4月から6月に生まれた人に比べて低いかどうかを検定しなさい。

**どの変数で評価すれば良いかを、検討しよう**

In [15]:
formula = 'mathscore ~ agese_q2 + agese_q3 + agese_q4'
mod = ols(formula, df)
res = mod.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              mathscore   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     6.736
Date:                Tue, 14 Jul 2026   Prob (F-statistic):           0.000157
Time:                        07:56:21   Log-Likelihood:                -16840.
No. Observations:                4536   AIC:                         3.369e+04
Df Residuals:                    4532   BIC:                         3.371e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    150.3634      0.294    512.093      0.000     149.788     150.939
agese_q2       0.1743      0.407      0.428      0.669      -0.624       0.973
agese_q3      -0.3462      0.417     -0.831      0.406      -1.163       0.471
agese_q4      -1.5581      0.425     -3.664      0.000      -2.392      -0.724
==============================================================================
Omnibus:                       32.519   Durbin-Watson:                   1.715
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               38.397
Skew:                           0.141   Prob(JB):                     4.59e-09
Kurtosis:                       3.352   Cond. No.                         4.79
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## (b)
間（a）の回帰式に、

1.   地域の大きさを表すダミー変数(comu_1 から comu_5)
2.   コンピュータが家庭にあるかどうかを示すダミー変数(computer)
3. 家庭の人数を表す変数(numpeople)
4. 母親の学歴を表すダミー変数(mothereduc_1 から mothereduc_5)
5. 父親の学歴を表すダミー変数(fathereduc_1 から fathereduc_5)


を、説明変数に加えたモデルを推定しなさい。


その結果をもとに、早生まれの人の成績が、4月から6月に生まれた人に比べて低いかどうかを検定しなさい

In [19]:
formula2 = 'mathscore ~ agese_q2 + agese_q3 + agese_q4 + comu_1 + comu_2 + comu_3 + comu_4 + comu_5 + numpeople + mothereduc_1 + mothereduc_2 + mothereduc_3 + mothereduc_4 + mothereduc_5 +  fathereduc_1 + fathereduc_2 + fathereduc_3 + fathereduc_4 + fathereduc_5 '
mod = ols(formula2, df)
res = mod.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              mathscore   R-squared:                       0.093
Model:                            OLS   Adj. R-squared:                  0.088
Method:                 Least Squares   F-statistic:                     19.32
Date:                Tue, 14 Jul 2026   Prob (F-statistic):           1.45e-78
Time:                        08:06:20   Log-Likelihood:                -16628.
No. Observations:                4536   AIC:                         3.331e+04
Df Residuals:                    4511   BIC:                         3.347e+04
Df Model:                          24
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                145.1622      2.671     54.354      0.000     139.926     150.398
numpeople[T.3]             2.2021      1.358      1.622      0.105      -0.460       4.864
numpeople[T.4]             3.1681      1.295      2.447      0.014       0.630       5.706
numpeople[T.5]             2.6523      1.302      2.037      0.042       0.100       5.204
numpeople[T.6]             2.2351      1.328      1.683      0.092      -0.368       4.838
numpeople[T.7]             2.6199      1.374      1.907      0.057      -0.073       5.313
numpeople[T.8 or more]    -0.0565      1.594     -0.035      0.972      -3.181       3.068
agese_q2                   0.1903      0.391      0.487      0.626      -0.576       0.956
agese_q3                  -0.4732      0.400     -1.184      0.236      -1.257       0.310
agese_q4                  -1.3447      0.408     -3.297      0.001      -2.144      -0.545
comu_1                     1.7463      2.338      0.747      0.455      -2.837       6.329
comu_2                     1.2948      2.328      0.556      0.578      -3.269       5.858
comu_3                    -0.2379      2.353     -0.101      0.919      -4.851       4.375
comu_4                     0.4809      2.338      0.206      0.837      -4.103       5.065
comu_5                     1.2859      2.361      0.545      0.586      -3.342       5.914
mothereduc_1              -2.7097      0.936     -2.896      0.004      -4.544      -0.875
mothereduc_2              -0.1926      0.471     -0.409      0.682      -1.116       0.730
mothereduc_3               1.7764      0.501      3.545      0.000       0.794       2.759
mothereduc_4               2.6351      0.557      4.730      0.000       1.543       3.727
mothereduc_5              -1.0381      1.743     -0.596      0.551      -4.455       2.378
fathereduc_1              -3.0729      0.822     -3.741      0.000      -4.683      -1.462
fathereduc_2              -0.4556      0.470     -0.969      0.333      -1.377       0.466
fathereduc_3               0.2660      0.707      0.376      0.707      -1.120       1.651
fathereduc_4               3.2563      0.471      6.911      0.000       2.333       4.180
fathereduc_5               6.5699      1.149      5.720      0.000       4.318       8.822
==============================================================================
Omnibus:                       38.880   Durbin-Watson:                   1.780
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               49.603
Skew:                           0.136   Prob(JB):                     1.69e-11
Kurtosis:                       3.435   Cond. No.                         58.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## (c)
数学の成績の代わりに、理科の成績(sciencescore)を用いて、問（a）,(b)の分析を行いなさい。数学と理科では、結果が異なるかどうかを議論しなさい。

### (c)-(a)

In [22]:
formula3 = 'sciencescore ~ agese_q2 + agese_q3 + agese_q4'
mod = ols(formula3, df)
res = mod.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           sciencescore   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.005
Method:                 Least Squares   F-statistic:                     8.527
Date:                Tue, 14 Jul 2026   Prob (F-statistic):           1.21e-05
Time:                        08:17:16   Log-Likelihood:                -16856.
No. Observations:                4536   AIC:                         3.372e+04
Df Residuals:                    4532   BIC:                         3.375e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    150.4531      0.295    510.544      0.000     149.875     151.031
agese_q2       0.2612      0.409      0.639      0.523      -0.540       1.063
agese_q3      -0.5426      0.418     -1.297      0.195      -1.363       0.278
agese_q4      -1.7171      0.427     -4.024      0.000      -2.554      -0.880
==============================================================================
Omnibus:                       91.444   Durbin-Watson:                   1.817
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              189.183
Skew:                          -0.064   Prob(JB):                     8.31e-42
Kurtosis:                       3.992   Cond. No.                         4.79
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### (c)-(b)

In [21]:
formula4 = 'sciencescore ~ agese_q2 + agese_q3 + agese_q4 + comu_1 + comu_2 + comu_3 + comu_4 + comu_5 + numpeople + mothereduc_1 + mothereduc_2 + mothereduc_3 + mothereduc_4 + mothereduc_5 +  fathereduc_1 + fathereduc_2 + fathereduc_3 + fathereduc_4 + fathereduc_5 '
mod = ols(formula4, df)
res = mod.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           sciencescore   R-squared:                       0.066
Model:                            OLS   Adj. R-squared:                  0.061
Method:                 Least Squares   F-statistic:                     13.19
Date:                Tue, 14 Jul 2026   Prob (F-statistic):           7.18e-51
Time:                        08:17:07   Log-Likelihood:                -16715.
No. Observations:                4536   AIC:                         3.348e+04
Df Residuals:                    4511   BIC:                         3.364e+04
Df Model:                          24
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                152.0487      2.722     55.849      0.000     146.711     157.386
numpeople[T.3]             0.2751      1.384      0.199      0.842      -2.438       2.989
numpeople[T.4]            -0.3108      1.320     -0.236      0.814      -2.898       2.276
numpeople[T.5]            -0.2561      1.327     -0.193      0.847      -2.858       2.345
numpeople[T.6]            -0.4616      1.354     -0.341      0.733      -3.115       2.192
numpeople[T.7]            -0.0221      1.400     -0.016      0.987      -2.767       2.723
numpeople[T.8 or more]    -1.7982      1.625     -1.107      0.268      -4.984       1.387
agese_q2                   0.3199      0.398      0.803      0.422      -0.461       1.101
agese_q3                  -0.5845      0.407     -1.435      0.151      -1.383       0.214
agese_q4                  -1.5084      0.416     -3.628      0.000      -2.323      -0.693
comu_1                    -2.3057      2.383     -0.968      0.333      -6.977       2.366
comu_2                    -2.6503      2.373     -1.117      0.264      -7.302       2.002
comu_3                    -4.1526      2.399     -1.731      0.083      -8.855       0.550
comu_4                    -3.1439      2.384     -1.319      0.187      -7.817       1.529
comu_5                    -2.6207      2.407     -1.089      0.276      -7.339       2.097
mothereduc_1              -1.5398      0.954     -1.614      0.107      -3.410       0.330
mothereduc_2              -0.1417      0.480     -0.295      0.768      -1.083       0.799
mothereduc_3               1.3315      0.511      2.607      0.009       0.330       2.333
mothereduc_4               1.3042      0.568      2.296      0.022       0.191       2.418
mothereduc_5              -2.9980      1.776     -1.688      0.092      -6.481       0.485
fathereduc_1              -2.0410      0.837     -2.437      0.015      -3.683      -0.399
fathereduc_2              -0.1229      0.479     -0.256      0.798      -1.063       0.817
fathereduc_3               1.3911      0.720      1.931      0.054      -0.021       2.803
fathereduc_4               3.3917      0.480      7.062      0.000       2.450       4.333
fathereduc_5               8.1104      1.171      6.927      0.000       5.815      10.406
==============================================================================
Omnibus:                       96.725   Durbin-Watson:                   1.867
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              201.246
Skew:                          -0.082   Prob(JB):                     2.00e-44
Kurtosis:                       4.019   Cond. No.                         58.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.